### ISSUE TITLE
Remove role and Minimum age

### ISSUE THREAD

**Issue by 213981320812390813201382091328** [uhidontkno/Artemis#19]
Hey,
please add an option that the verify will remove role instead of add role, and you can choose in the /setup.
And add an option to choose "no minimum age" meaning everyone can verify even if they just created their account.

**Comment by uhidontkno** [comment]
Remove role functionality will not be implemented, but the no minimum age will be implemented. I have moved to GitLab so this repo will not be updated.

**Comment by 213981320812390813201382091328** [comment]
Why you wont add remove role functionality?

**Comment by uhidontkno** [comment]
> Why you wont add remove role functionality?

You should lock your server behind a Verified role instead of removing access by giving an Unverified role on join then removing after verify.
